CONFIG_GPIO=y
CONFIG_LOG=y

CONFIG_BLINK_SLEEP_500_MS=y
CONFIG_LED_ADVANCED_SETTINGS=y
CONFIG_LED_BRIGHTNESS=70
CONFIG_LED_FADE_DURATION_MS=100
CONFIG_LED_DEBUGGING=y

CONFIG_APP_HEARTBEAT_PERIOD_MS=1000